module.exports = {
  title: "ryanbae.dev",
  description: "소통을 좋아하는 프론트엔드 개발자입니다.",
  author: "Ryan",
  siteUrl: "https://devhudi.github.io/gatsby-starter-hoodie/",
  links: {
    github: "https://github.com/ryanbae94",
    linkedIn: "https://www.linkedin.com/in/junhyungbae/",
    facebook: "https://www.facebook.com",
    twitter: "https://twitter.com",
    x: "https://x.com",
    instagram: "https://www.instagram.com",
    medium: "https://medium.com",
    blogger: "https://blogger.com",
    email: "mailto:ryanbae94@gmail.com",
    resume: "",
    link: "",
  },
  useAbout: true,
  // See https://giscus.app/
  giscus: {
    repo: "devHudi/gatsby-starter-hoodie",
    repoId: "MDEwOlJlcG9zaXRvcnkzNjk4NjMzNTg=",
    category: "Comments",
    categoryId: "DIC_kwDOFguqvs4ChwGy",
    mapping: "pathname",
    strict: "0",
    reactionsEnabled: "1",
    inputPosition: "bottom",
    lang: "en",
  },
}
